# Generated by Django 4.0.8 on 2023-01-16 04:12

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='modified at')),
                ('uuid', django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True)),
                ('is_removed', models.BooleanField(default=False, help_text='used to signal that it is removed', verbose_name='remove status')),
                ('payment_method', models.CharField(blank=True, max_length=75)),
                ('bank', models.CharField(blank=True, max_length=75)),
                ('delivery_date', models.DateField()),
                ('is_pending', models.BooleanField(default=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('company', models.CharField(max_length=75)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='modified at')),
                ('uuid', django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True)),
                ('is_removed', models.BooleanField(default=False, help_text='used to signal that it is removed', verbose_name='remove status')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
