# Generated by Django 4.0.8 on 2023-01-16 04:12

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='modified at')),
                ('uuid', django_extensions.db.fields.ShortUUIDField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True)),
                ('is_removed', models.BooleanField(default=False, help_text='used to signal that it is removed', verbose_name='remove status')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed', regex='\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(max_length=75)),
                ('province', models.CharField(max_length=75)),
                ('department', models.CharField(blank=True, max_length=75)),
                ('company', models.CharField(max_length=75)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
